import type { Metadata } from "next";
import "slick-carousel/slick/slick-theme.css";
import "slick-carousel/slick/slick.css";
import Footer from "./component/Footer";
import Header from "./component/Header";
import "./globals.css";
import "./styles/responsive.css";
import "./styles/style.css";

export const metadata: Metadata = {
  title: "Next Ecommerce",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Header />
        <div className="m-auto">{children}</div>
        <Footer />
      </body>
    </html>
  );
}
